[theme]
primaryColor = "#2F39A9"
backgroundColor = "#080B24"
secondaryBackgroundColor = "#0B1030"
textColor = "#EAF2FF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
