[theme]
primaryColor = "#8E1EA2"
backgroundColor = "#12041A"
secondaryBackgroundColor = "#1B0724"
textColor = "#FFF7FD"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
